# Version of docker-compose.
version: '3'

# Containers we're going to run.
services:
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory.
      context: .
    environment:
      # Variables to connect to our Postgres server.
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: figours_dev
      PGPORT: 5432
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container.
      - '4000:4000'
  
